get:
  summary: Get a specific product rating info
  description: This endpoint allows the front end to get information about the rating of a specific product
  parameters:
    - name: productId
      in: path
      required: true
      description: The id of the product
      schema:
        type: integer
    - name: minAge
      in: query
      required: true
      description: The minimum age of the personas
      schema:
        type: integer
    - name: maxAge
      in: query
      required: true
      description: The maximum age of the personas
      schema:
        type: integer
    - name: female
      in: query
      required: true
      description: include female personas or not 
      schema:
        type: boolean
    - name: male
      in: query
      required: true
      description: include male personas or not
      schema:
        type: boolean
    - name: selectedPersonas
      in: query
      required: true
      description: The selected personas
      schema:
        type: array
        items:
          type: integer
          description: The id of the persona
    - name: selectedDomains
      in: query
      required: true
      description: The selected domains
      schema:
        type: array
        items:
          type: integer
          description: The id of the domain
    - name: featuresOn
      in: query
      required: true
      description: The features that are turned on
      schema:
        type: boolean
      

  security:
    - BearerAuth: []
  responses:
    '200':
      description: OK
      headers:
        Set-Cookie:
          description: |
            refreshed access token which will be valid for another 10 minutes
            - access_token: The JWT token to be used for authentication, this is valid for 10 minutes
          schema:
            $ref: '../components/schemas/AccessTokenHeader.yml'
      content:
        application/json:
          schema:
            $ref: '../components/schemas/ProductRatingResponse.yml'
    '400':
      $ref: '../components/responses/BadRequest.yml'
    '401':
      $ref: '../components/responses/Unauthorized.yml'
    '500':
      $ref: '../components/responses/InternalServerError.yml'
