openapi: 3.0.0
paths:
  /login:
    $ref: 'paths/login.yml'
  /auth:
    $ref: 'paths/auth.yml'
  /product/{productId}:
    $ref: 'paths/product/productInfo.yml'
  /product/{productId}/persona:
    $ref: 'paths/product/persona.yml'
  /product/{productId}/filter:
    $ref: 'paths/product/productFilter.yml'
  /product/{productId}/rating:
    $ref: 'paths/product/productRating.yml'
  /sharedProduct/{productId}/rating':
    $ref: 'paths/sharedProduct/sharedProductRating.yml'
  /product/{productId}/feature/{featureId}:
    $ref: 'paths/product/featureDetail.yml'
  /sharedProduct/{productId}/feature/{featureId}/rating':
    $ref: 'paths/sharedProduct/sharedFeatureDetail.yml'
  /product/{productId}/codesigner:
    $ref: 'paths/product/codesigner.yml'
  /product/{productId}/codesigner/{codesignerId}:
    $ref: 'paths/product/codesignerSurvey.yml'
  /product/{productId}/shareLink:
    $ref: 'paths/product/shareLink.yml'
  /product/{productId}/shareViaEmail:
    $ref: 'paths/shareViaEmail.yml'
  /survey/{surveyId}/productInfo:
    $ref: 'paths/survey/surveyProductInfo.yml'
  /survey/{surveyId}/domains:
    $ref: 'paths/survey/surveyDomains.yml'
  /survey/{surveyId}/rating:
    $ref: 'paths/survey/surveyRating.yml'
  /survey/{surveyId}/product/{productId}/feature/{featureId}:
    $ref: 'paths/survey/surveyFeatureDetail.yml'
  /survey/{surveyId}/shareLink:
    $ref: 'paths/survey/surveyShareLink.yml'
  /product/generateReport:
    $ref: 'paths/generateReport.yml'
info:
  title: Mavie API
  description: API for Mavie Customer Backend
  version: 2.0.0
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ProductFilterResponse:
      $ref: 'components/schemas/ProductFilterResponse.yml'
    Domain:
      $ref: 'components/schemas/Domain.yml'
    Feature:
      $ref: 'components/schemas/Feature.yml'
    Persona:
      $ref: 'components/schemas/Persona.yml'
  responses:
    BadRequest:
      $ref: 'components/responses/BadRequest.yml'
    InternalServerError:
      $ref: 'components/responses/InternalServerError.yml'
    Unauthorized:
      $ref: 'components/responses/Unauthorized.yml'
    NotFound:
      $ref: 'components/responses/NotFound.yml'