openapi: 3.0.0
paths:
  /login:
    $ref: 'paths/login.yml'
  /refresh_token:
    $ref: 'paths/refreshToken.yml'
  /product_filter/{id}:
    $ref: 'paths/productFilter.yml'
info:
  title: Mavie API
  description: API for Mavie Customer Backend
  version: 1.0.0
components:
  schemas:
    ProductFilterResponse:
      $ref: '#/components/schemas/ProductFilterResponse'
    Domain:
      $ref: '#/components/schemas/Domain'
    Feature:
      $ref: '#/components/schemas/Feature'
    Persona:
      $ref: '#/components/schemas/Persona'
  responses:
    BadRequest:
      $ref: '#/components/responses/BadRequest'
    InternalServerError:
      $ref: '#/components/responses/InternalServerError'
    Unauthorized:
      $ref: '#/components/responses/Unauthorized'
    NotFound:
      $ref: '#/components/responses/NotFound'