openapi: 3.0.0
paths:
  /login:
    $ref: 'paths/login.yml'
  /refresh_token:
    $ref: 'paths/refreshToken.yml'
  /product_filter/{id}:
    $ref: 'paths/productFilter.yml'
info:
  title: Mavie API
  description: API for Mavie Customer Backend
  version: 1.0.0
