openapi: 3.0.0
paths:
  /login:
    $ref: 'paths/login.yml'
  /auth:
    $ref: 'paths/auth.yml'
  /persona:
    $ref: 'paths/persona.yml'
  /product/{productId}:
    $ref: 'paths/productInfo.yml'
  /product/{productId}/filter:
    $ref: 'paths/productFilter.yml'
  /product/{productId}/rating:
    $ref: 'paths/productRating.yml'
  /product/{productId}/feature/{featureId}:
    $ref: 'paths/featureDetail.yml'
  /product/{productId}/codesigner:
    $ref: 'paths/codesigner.yml'
  /product/{productId}/shareLink:
    $ref: 'paths/shareLink.yml'
  /product/{productId}/verifyCode:
    $ref: 'paths/verifyCode.yml'
  /product/{productId}/shareViaEmail:
    $ref: 'paths/shareViaEmail.yml'
info:
  title: Mavie API
  description: API for Mavie Customer Backend
  version: 2.0.0
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ProductFilterResponse:
      $ref: 'components/schemas/ProductFilterResponse.yml'
    Domain:
      $ref: 'components/schemas/Domain.yml'
    Feature:
      $ref: 'components/schemas/Feature.yml'
    Persona:
      $ref: 'components/schemas/Persona.yml'
  responses:
    BadRequest:
      $ref: 'components/responses/BadRequest.yml'
    InternalServerError:
      $ref: 'components/responses/InternalServerError.yml'
    Unauthorized:
      $ref: 'components/responses/Unauthorized.yml'
    NotFound:
      $ref: 'components/responses/NotFound.yml'