get:
  summary: Get a specific product rating info
  description: This endpoint allows the front end to get information about the rating of a specific product
  parameters:
    - name: productId
      in: path
      required: true
      description: The id of the product
      schema:
        type: integer

  responses:
    '200':
      description: OK
      headers:
        Set-Cookie:
          description: |
            refreshed access token which will be valid for another 10 minutes
            - access_token: The JWT token to be used for authentication, this is valid for 10 minutes
          schema:
            $ref: '../../components/schemas/AccessTokenHeader.yml'
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/ProductRatingResponse.yml'
    '400':
      $ref: '../../components/responses/BadRequest.yml'
    '401':
      $ref: '../../components/responses/Unauthorized.yml'
    '500':
      $ref: '../../components/responses/InternalServerError.yml'
