type: object
properties:
  domains:
    type: array
    description: The list of domains for the product
    items:
      $ref: './Domain.yml'
  features:
    type: array
    description: The list of features for the product
    items:
      $ref: './Feature.yml'