type: object
properties:
  domains:
    type: array
    description: The list of domains for the product
    items:
      $ref: './Domain.yml'
  features:
    type: array
    description: The list of features for the product
    items:
      $ref: './Feature.yml'
  personas:
    type: array
    description: The list of personas for the product
    items:
      $ref: './Persona.yml'
  ageRange:
    type: object
    description: The age range for the product
    properties:
      minAge:
        type: integer
        description: The minimum age for the product
      maxAge:
        type: integer
        description: The maximum age for the product