type: object
properties:
  brand:
    type: string
    description: The brand of the product
  brandIcon:
    type: string
    description: The brand icon of the product
  description:
    type: string
    description: The description of the product
  image:
    type: string
    description: The image link of the product
  modelName:
    type: string
    description: The model name of the product
  productCategoryName:
    type: string
    description: The product category of the product
  expertOpinion:
    type: string
    description: The expert opinion of the product
  access_token:
    type: string
    description: The new JWT token to be used for authentication, this is valid for 10 minutes
